import Head from 'next/head'
import SignUp from './signUp'
import SignIn from './signIn'

export default function Home() {


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        {/* <script src="https://upload-widget.cloudinary.com/global/all.js" type="text/javascript"></script>   */}
      </Head>
      <main>
          <SignUp/>
      </main>
      </>
  )
}
